### PR TITLE
Minor fixes to the Gradle build

### PR DESCRIPTION
**Pull request by eskatos**
See each commit message for details

### CODE REVIEW

**Comment by maltaisn** [comment]
Thanks a lot!

I'm getting an error launching the desktop configuration:
```text
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Unrecognized option: -XstartOnFirstThread
```
I'm still using JDK 8 maybe it's related? It worked fine for me without the argument.

Also what's wrong with setting the source sets? How will they be found otherwise?
And what do the extra gradlew jvm arguments do?

**Comment by maltaisn** [comment]
Actually it seems that the `-XstartOnFirstThread` is [only needed (and available) on OSX](http://forum.lwjgl.org/index.php?topic=6480.0). So I think it would be better to do instead:

```
if (System.getProperty("os.name").toLowerCase().indexOf("mac") != -1) {
    jvmArgs("-XstartOnFirstThread")
}
```

**Comment by eskatos** [comment]
> Also what's wrong with setting the source sets? How will they be found otherwise?

Mixing Java and Kotlin in the same source sets in Gradle isn't recommended, see https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:separate_language_source_files. It is preferable to keep `src/*/java` and `src/*/kotlin` which is the default. The removed source set configuration was changing the default.

> And what do the extra gradlew jvm arguments do?

They limit the amount of memory allocated by the Gradle "client" jvm, the one started by the wrapper that communicates with the daemon. It's a change coming from Gradle 5, see https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:default_memory_settings

**Comment by maltaisn** [comment]
Talking about defaults, do you think it would be better to use the default android structure? That would remove the need for the `sourceSets` block in the android build script. Here's the [default source sets for android](https://developer.android.com/studio/build/build-variants#sourcesets). That would involve:
- Copying natives libraries to `android/src/main/jniLibs` instead of `android/libs`.
- Having the assets folder at `src/main/assets`.
- Moving `android/res` folder to `android/src/main/res`.

In my projects I usually have the assets folder at the root and use a copy task to copy it to a `android/assets` folder, or in this case, a `android/src/main/assets` folder, which is added to .gitignore.

I already moved the manifest file under `android/src/main`, it used to be in `android/` and require a manifest attribute in source sets configuration.

**Comment by eskatos** [comment]
Hi @maltaisn, I suppose you closed the PR by accident.

I think that making things closer to the defaults is a good idea in general, less surprise.
Moving the manifest to it's default location sounds good.
I can have a look at `assets/` later.

Could we merge this first PR already?

**Comment by maltaisn** [comment]
Sorry for the confusion. I had already merged your first commits. I didn't merge the last commit since I had already done the changes locally. I just merged it to see if github would mark the pull request as merged but it didn't and reopen is blocked.

**Comment by maltaisn** [comment]
I made the changes I talked about in the [`alternative`](https://github.com/maltaisn/libgdx-kotlin-template/tree/alternative) branch if you're interested.

**Pull request closed without merging**
